repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
- name: ingress
  chart: ./ingress
  installed: false
- name: k8s-monitoring
  namespace: monitoring
  chart: grafana/k8s-monitoring
  createNamespace: true
  values:
  - cluster:
      name: my-cluster
    destinations:
    - name: local-mimir
      type: prometheus
      url: http://mimir-nginx.monitoring.svc.cluster.local.:80/api/v1/push
    alloy-metrics:
      enabled: true
    clusterMetrics:
      enabled: true
      controlPlane:
        enabled: true
- name: mimir
  namespace: monitoring
  chart: grafana/mimir-distributed
  createNamespace: true
  values:
  - mimir:
      structuredConfig:
        ingester:
          ring:
            replication_factor: 1
    ingester:
      replicas: 1
      zoneAwareReplication:
        enabled: false
    store_gateway:
      replicas: 1
      zoneAwareReplication:
        enabled: false
    federationFrontend:
      replicas: 1
    minio:
      replicas: 1
    querier:
      replicas: 1
    query_scheduler:
      replicas: 1
- name: grafana
  namespace: monitoring
  chart: grafana/grafana
  createNamespace: true
  values:
  - grafana-values.yaml
  